version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unparam
    - unconvert
    - gocritic
    - gocyclo
    - dupl
    - gosec
    - nolintlint
    - whitespace
